Repository selsa-inube/inubekit-icon, pull requests merged in 2024-03, with the labels that each got.

#8 Refactor appearance prop so it isn't of type string, but type "primary" | "warning" | ...
  package-lock.json
  package.json
  src/Icon/Icon.stories.tsx
  src/Icon/index.tsx
  src/Icon/props.ts
  src/Icon/styles.js
Labels: minor

#9 Release new version 1.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#10 Implement try..catch in props of type function
  package-lock.json
  package.json
  src/Icon/index.tsx
  src/Icon/props.ts
Labels: minor

#11 Publish new version 1.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#12 Adjust and export interfaces
  src/Icon/index.tsx
  src/Icon/props.ts
  src/index.ts
Labels: minor

#13 Publish new version 1.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#14 Update inubekit/icon to storybook v8
  package-lock.json
  package.json
Labels: dependencies
