Repository selsa-inube/inubekit-icon, pull requests merged in 2024-07, with the labels that each got.

#19 Update foundations dependencies
  package.json
Labels: minor, dependencies

#21 feat: adjust values in spacing and variant props
  src/Icon/Icon.stories.tsx
  src/Icon/index.tsx
  src/Icon/props.ts
  src/Icon/styles.js
Labels: major

#22 fix: increase padding in wide and compact spacings
  src/Icon/styles.js
Labels: patch
